ThrottleService/urls.py
"""ThrottleService URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Fun'Service',ction views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = [
    path('', include('common.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('service/', include('service.urls')),
    re_path('^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

handler404 = 'common.views.handler404'
handler500 = 'common.views.handler500'
handler400 = 'common.views.handler400'

account/urls.py
from django.urls import path
from .views import signup, change_password
from django.contrib.auth import views as auth_views

app_name = 'account'
urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='home.html'), name='logout'),
    path('change_password/', change_password, name='change_password')
]

common/urls.py
from django.urls import path, re_path
from .views import home, new_throttle, edit_throttle, delete_throttle

app_name = 'common'
urlpatterns = [
    path('', home, name='home'),
    path('new_throttle/', new_throttle, name='new_throttle'),
    re_path('^edit_throttle/(?P<pk>\d+)/', edit_throttle, name='edit_throttle'),
    re_path('^delete_throttle/(?P<pk>\d+)/', delete_throttle, name='delete_throttle'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Throttle Service{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    {% block stylesheet %}{% endblock %}
</head>
<body>
{% block body %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'common:home' %}">Throttle Service</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu"
                    aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mainMenu">
                {% if user.is_authenticated %}
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                {#                                <a class="dropdown-item" href="#">My account</a>#}
                                <a class="dropdown-item" href="{% url 'account:change_password' %}">Change password</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'account:logout' %}">Log out</a>
                            </div>
                        </li>
                    </ul>
                {% else %}
                    <form class="form-inline ml-auto">
                        <a href="{% url 'account:login' %}" class="btn btn-outline-secondary">Log in</a>
                        <a href="{% url 'account:signup' %}" class="btn btn-primary ml-2">Sign up</a>
                    </form>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="container">
        <ol class="breadcrumb my-4">
            {% block breadcrumb %}
            {% endblock %}
        </ol>
        {% block content %}
        {% endblock %}

    </div>
{% endblock body %}

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/changePassword.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="text-center logo my-4">
            <a href="{% url 'common:home' %}">Throttle Service</a>
        </h1>
        <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 col-sm-8">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">Change password</h3>
                        <form method="post" novalidate>
                            {% csrf_token %}
                            {% include 'includes/form.html' %}
                            <button type="submit" class="btn btn-primary btn-block">Log in</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block breadcrumb %}
    {% if user.is_authenticated %}
        <li class="breadcrumb-item active">Entities</li>
    {% else %}
        <li class="breadcrumb-item active">Login or Sign up first</li>
    {% endif %}
{% endblock %}

{% block content %}
    <table class="table">
        <thead class="thead-inverse">
        <tr>
            {% if user.is_authenticated %}
                <th>Pattern</th>
                <th>Limit times</th>
                <th></th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for throttle in throttles %}
            <tr>
                <td>
                    <a href="{{ throttle.pattern }}">{{ throttle.pattern }}</a>
                </td>
                <td>
                    <span class="text-muted d-block">{{ throttle.number }}/{{ throttle.limit }}</span>
                </td>
                <td>
                    <a href="{% url 'common:edit_throttle' throttle.pk %}" class="btn btn-outline-info">Edit</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if user.is_authenticated %}
        <div class="mb-4">
            <a href="{% url 'common:new_throttle' %}" class="btn btn-primary">New throttle</a>
        </div>
    {% endif %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="text-center logo my-4">
            <a href="{% url 'common:home' %}">Throttle Service</a>
        </h1>
        <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 col-sm-8">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">Log in</h3>
                        <form method="post" novalidate>
                            {% csrf_token %}
                            {% include 'includes/form.html' %}
                            <button type="submit" class="btn btn-primary btn-block">Log in</button>
                        </form>
                    </div>
                    <div class="card-footer text-muted text-center">
                        New to Throttle Service <a href="{% url 'account:signup' %}">Sign up</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/new_throttle.html
{% extends 'base.html' %}
{% load filters %}

{% block title %}{{ title }}{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'common:home' %}">Home</a></li>
    <li class="breadcrumb-item active">{{ title|contain_create }}</li>
{% endblock %}

{% block content %}
    <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">{{ title|contain_create }}</button>
        {% if title|contain_create == 'Edit' %}
            <a href="{% url 'common:delete_throttle' pk %}" class="btn btn-danger">Delete</a>
        {% endif %}
    </form>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="text-center logo my-4">
            <a href="{% url 'common:home' %}">Throttle Service</a>
        </h1>
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">Sign up</h3>
                        <form method="post" novalidate>
                            {% csrf_token %}
                            {% include 'includes/form.html' %}
                            <button type="submit" class="btn btn-primary btn-block">Create an account</button>
                        </form>
                    </div>
                    <div class="card-footer text-muted text-center">
                        Already have an account? <a href="{% url 'account:login' %}">Log in</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}